name: Greetings

on: [pull_request, issues, fork]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
    steps:
      - uses: actions/first-interaction@v1
        with: 
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '<h1>Hi there! You are welcome to contribute to this repository.</h1>'
          pr-message: 'Thanks for your contribution. Will revert back soon! :rocket'


      
